### ISSUE TITLE
Workflow doesn't work for normal Harvest users

### ISSUE THREAD

**Issue by MyAudioDNA** [ajilderda/alfred-harvest-v2#3]
This workflow will only work if you are an Admin or Project Manager level users. Otherwise, the list of projects and tasks can't populate as the Harvest API does not allow access to those functions for lower level users.

**Comment by ajilderda** [comment]
Hi @MyAudioDNA, I was looking at the authentication page (https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/) which states:
> Personal Access Tokens have the all scope by default, so you have full access to all of your accounts.

As a non-admin user are you able to create a Personal Access Token? Have you tried this?:
https://id.getharvest.com/developers

**Comment by MyAudioDNA** [comment]
Yes I can create a Personal Access Token as a non-admin user, however that token will not allow access to Projects or Tasks.

As you can see at the top of the Projects documentation (https://help.getharvest.com/api-v2/projects-api/projects/projects/)

> Admin or Project Manager permissions required.

**Comment by ajilderda** [comment]
Ah I see, that's too bad. I'm afraid there's nothing I can do about this, so closing this issue. Thanks for reporting!

**Comment by donaldguy** [comment]
I believe all the information you need should be fetchable via `https://api.harvestapp.com/api/v2/users/me/project_assignments` for non-admin users:

https://help.getharvest.com/api-v2/users-api/users/project-assignments/

which gives non-admin users access to all of their own project and task assignments (including pertinently the relevant ids that can be passed onto `/v2/time_entries`)

I'm gonna try to throw together a fork here for an hour or two but idk that I'mma have the patience to see it through, `node` is not my most comfortable environment

**Comment by donaldguy** [comment]
Potentially fixed in #9

**Comment by ajilderda** [comment]
A new release with @donaldguy's fix can be found here: https://github.com/ajilderda/alfred-harvest-v2/releases/tag/1.1.3

@MyAudioDNA Can you let me know if this is working for you?
