### ISSUE TITLE
I see time entries for the entire team

### ISSUE THREAD

**Issue by nourmalaeb** [ajilderda/alfred-harvest-v2#4]
Starting, stopping, and adjusting timers works really well, but when I go to adjust a timer, all of the day's timers from my entire Harvest team are shown. I'd love for a way to show just my timers so I don't change my coworker's entry by accident.

**Comment by ajilderda** [comment]
Thanks for reporting! As I'm the only user in my team I wasn't aware of this. I'll try to look into this issue this weekend.

**Comment by ajilderda** [comment]
Hi @nourmalaeb, I've just created a release @ https://github.com/ajilderda/alfred-harvest-v2/releases/tag/1.1.1 Can you please try this one to see if it fixes your issue? You do need to run the setup again (run `hvs` and follow the instructions).

**Comment by nourmalaeb** [comment]
Thank you! I've installed that release, but I'll need to wait for my teammates to put in some entries to check if it's working. Will report back soon.

**Comment by nourmalaeb** [comment]
It looks like it worked! Thanks @ajilderda.

**Comment by ajilderda** [comment]
Great! 👍
