### ISSUE TITLE
Alfred version

### ISSUE THREAD

**Issue by tgrrr** [ajilderda/alfred-harvest-v2#7]
This doesn't load in Alfred 3, is that because this workflow is only for Alfred 4? Are you using the new workflow objects?

It's fine if that's the case, it might just be worth updating the readme

**Comment by ajilderda** [comment]
Hi @tgrrr, yes this workflow is indeed using some of the newer workflow objects and because of that will only work in Alfred v4+. Will update the readme. Thanks!
