### ISSUE TITLE
Failed to list projects

### ISSUE THREAD

**Issue by verwinv** [ajilderda/alfred-harvest-v2#8]
Upon typing the _hvn_ command, the _Fetching Harvest projects_ turns into a _Failed to list projects_ message. How could I best troubleshoot this issue? Much thanks.

**Comment by donaldguy** [comment]
I attached a debug util to the list-projects filter and it would appear the problem is #3 - that the project and task endpoints this workflow depends on are only avaliable to admins and project managers

As I said in my comment on that issue, I believe this should be work-aroundable

**Comment by ajilderda** [comment]
Hi @verwinv, I've created a new release which you can find here: 
https://github.com/ajilderda/alfred-harvest-v2/releases/tag/1.1.3

Can you please check if that is working for you?

**Comment by aprice42** [comment]
Hi, I am working with v 1.1.3 and not able to see my projects either. Though my experience is a little different. When I use a command like `hvn` I just see search engine options, as if I want to search for the term "hvn". 

Perhaps I am missing something from the setup step? I input my api token and account id, but after that I don't see any confirmation or anything like that. 

Two considerations, one, my account is also connected to Forecast, could that be causing a problem? And I did have the [old harvest workflow](https://github.com/tinystride/alfred-harvest) installed previously, maybe something I need to do to clean that up?

**Comment by verwinv** [comment]
Hi @ajilderda, thanks for the update! For me, the new release solves the issue perfectly. I can see the project list and initiate the timer now. I indeed do not have admin rights to this account, as @donaldguy predicted. Much appreciated!
